# Generated by Django 4.2.4 on 2024-10-21 16:22

import Djangoadvanceproject.threedmodel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threedmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='threedmodel_photo',
            field=models.ImageField(upload_to='threedmodel_photos/', validators=[Djangoadvanceproject.threedmodel.models.MaxFileSizeValidator(limit_value=12582912)]),
        ),
    ]
