# Generated by Django 4.2.4 on 2024-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='threeduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='threeduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='last name'),
        ),
    ]
