# Generated by Django 4.2.4 on 2024-10-20 15:29

import Djangoadvanceproject.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedphoto',
            name='photo',
            field=models.ImageField(upload_to='threed_photos', validators=[Djangoadvanceproject.photos.models.MaxFileSizeValidator(limit_value=12582912)]),
        ),
    ]
