# Generated by Django 4.2.4 on 2024-10-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_threedphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threedphoto',
            old_name='location',
            new_name='photo_name',
        ),
        migrations.AddField(
            model_name='threedphoto',
            name='photo_tags',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
