# Generated by Django 4.2.4 on 2024-10-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocomment',
            old_name='pet_photo',
            new_name='threed_photo',
        ),
        migrations.RenameField(
            model_name='photolike',
            old_name='pet_photo',
            new_name='threed_photo',
        ),
    ]
