# Generated by Django 4.2.4 on 2024-10-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_threedphoto_photo'),
        ('common', '0002_rename_pet_photo_photocomment_threed_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='threed_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.threedphoto'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='threed_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.threedphoto'),
        ),
    ]
